name: Country Commercial Guides
pygments: true

markdown: rdiscount
exclude:
  - .bundle
  - .git
  - .gitignore
  - bin
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - source
  - Rakefile

source: .
destination: ../public/ccg
baseurl: "/ccg"